### ISSUE TITLE
WKV is numerically unstable

### ISSUE THREAD

**Issue by mrsteyk** [tensorpro/jax-rwkv#1]
after certain amount of layers it starts to make NaNs and INFs. Tested with 430m model.

`invalid value (inf) encountered in jit(convert_element_type)` on the line that does `return (a/b)[0].astype(dtype)`

**Comment by mrsteyk** [comment]
Upon cleanstating wasn't able to reproduce it again... argh, hate it when that happens, sorry.

**Comment by mrsteyk** [comment]
Was able to reproduce with `[0]*8`, highest could go without overflow is `7`.

**Comment by mrsteyk** [comment]
Using the core provided in [message in #wkv_kernel in #dev-geeral](https://discord.com/channels/992359628979568762/1059797950747922482/1060128140975943742) and [poorly rewriting it into jax](https://github.com/mrsteyk/RWKV-LM-jax/blob/3b70c7e0e3f254c4563cdc150e220eca554fe2dc/model.py#L137) seems to make it mostly match what Python+Pytorch give out.

**Comment by tensorpro** [comment]
good catch, thanks! I'll look into that approach

**Comment by tensorpro** [comment]
Using BlealTan's fix.
